### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by wangel13** [orphenxy/hooks-storage#1]
On page https://github.com/orphenxy/hooks-storage/blob/master/API.md.

Last header must be `useKeyPress`, not `useLocalStorage`.

![hooks_storage_API_md_at_master_·_orphenxy_hooks_storage](https://user-images.githubusercontent.com/1074859/82540363-9efc0d00-9b57-11ea-8a65-49f3770e0194.png)

**Comment by bulatzaliaev** [comment]
@WaNgeL-SaTaR thank you for the issue report. I've fixed that part of documentation. Enjoy using the package:)
